name: Run Qodo-Cover
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize # Thêm sự kiện này để chạy khi có thay đổi mới trong PR


permissions:
  pull-requests: write # Allows commenting on pull requests
  contents: write # Allows reading and writing files

jobs:
  run-qodo-cover:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository  # Thêm bước này để lấy mã nguồn
        uses: actions/checkout@v3

      - name: Run qodo-cover
        uses: qodo-ai/qodo-ci/.github/actions/qodo-cover@v0.1.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          model: gpt-4o

        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          github_action_config.auto_review: "true"

      - name: Debug Git Repository
        run: |
          ls -la
          git status
          git remote -v
